### PR TITLE
feat: landing page 

### PR DESCRIPTION
**Pull request by Seyijo**
image
## landing page

### CODE REVIEW

**Review by johnotu — CHANGES_REQUESTED** [review]
@Seyijo Please read the issue description and follow the specs outlined there

**Comment by Seyijo** [comment]
> @Seyijo Please read the issue description and follow the specs outlined there

Roger that!

**Comment by johnotu** [comment]
Hello @Seyijo, are you still working on this?

**Comment by johnotu** [comment]
Someone else will have to take over this since we've not heard from @Seyijo in a while. Closing it out

**Pull request closed without merging**
