### PR TITLE
feat: information card

### PR DESCRIPTION
**Pull request by toby-adedipe**
This allows us to display information in well color-coded cards for better user experience.
Added react-router dom and added font awesome to the project as well.

### CODE REVIEW

**Review by Abuh05 — DISMISSED** [review]

**Comment by johnotu** [comment]
Hello @toby-adedipe, related issue requires only component-related files in the respective folder. Please edit your PR to reflect that

**Review by johnotu — CHANGES_REQUESTED** [review]
Hello @toby-adedipe, related issue requires only component-related files in the respective folder. Please edit your PR to reflect that

**Comment by toby-adedipe** [comment]
Made the neccesary changes.

**Review by johnotu — APPROVED** [review]

**Comment by johnotu** [comment]
Merging this with admin privileges since we can no longer wait for reviewers

**Pull request merged**
