### PR TITLE
Chore: Added font awesome to the project

### LINKED ISSUE #18: Font-Awesome
Add the Font-Awesome Icon pack to the project so it can be used by app-wide.

### PR DESCRIPTION
**Pull request by toby-adedipe**
Added font awesome to the project to enable us make use of fontt awesome icons

This allows us to make use of the wide array of font awesome icons in the front end of our project.

Fixes #18

### CODE REVIEW

**Review by johnotu — CHANGES_REQUESTED** [review]
@toby-adedipe So this Fort awesome for some reason requires 3 packages which seem an overkill just to get access to icons. Can we use the regular Font-awesome package `yarn add font-awesome` and then import the minified CSS from *index.js* just like we do for Bootstrap. This will on the whole require changes to just two files *package.json* and *index.js* in the project root.

**Comment by toby-adedipe** [comment]
@johnotu I'd try that, but i followed the instructions on the font awesome website to install it like this for react. I reckon the extra installations are for the icons themselves.

**Comment by johnotu** [comment]
Hello @toby-adedipe How far with this?

**Review by Abuh05 — APPROVED** [review]

**Comment by johnotu** [comment]
Closing this out since it's been fixed in [this pr](https://github.com/BuildForSDGCohort2/Team-023-Frontend/pull/26)

**Pull request closed without merging**
